### ISSUE TITLE
Change propagation in a batch with late bindings - P(1) ~12

### ISSUE THREAD

**Issue by dylanrtt** [canjs/can-compute#10]
![compute diagram](https://cloud.githubusercontent.com/assets/11302736/16070760/776b2d44-328c-11e6-82bf-ad3670c06abc.png)

The computes with red outlines (*child* and *grandChild*) are initially bound. The dashed line represents a late binding that will be created only when *parentB* has a specific value.

When *parentA* and *parentB* are both changed in a batch, when the batch ends, *grandChild* re-evaluates first, during which it reads *child* for the first time (new binding). Since *child* has not yet been re-evaluated (its dependency *parentA* changed), the cached value is provided, which is obviously bad because it means *grandChild* could compute a result that no longer matches the current state.

I'm also curious about why *grandChild* is re-evaluated first. Outside of a batch, it would be the reverse order.

http://jsbin.com/lifawuguyi/1/edit?js,console,output

**Comment by justinbmeyer** [comment]
Hmmm, so it seems like the solution might be to see we are reading `childA` and then make sure it is fully updated before continuing.

**Comment by justinbmeyer** [comment]
This should be fixed in 2.3.

**Comment by justinbmeyer** [comment]
A version of the jsbin that I can understand a bit more: http://justinbmeyer.jsbin.com/vezipe/1/edit?js,console

Thanks @dylanrtt for reporting this!

**Comment by justinbmeyer** [comment]
Unfortunately, the only solution I can come up with now is a  __mark and then update__ strategy combined with making computes marked for update able to immediately re-evaluate themselves when read.  I've been trying to avoid this because it will make compute updates a bit more expensive. 

Here's how it can work with arbitrary compute depth.  I've changed the example to use a great grandchild compute (`gg1`). 

The initial compute setup looks like this:

![presentation2](https://cloud.githubusercontent.com/assets/78602/16087336/4c09bac4-32e8-11e6-9745-f90d58267483.png)


Notice that `gg1` doesn't initially depend on `g1`.  That's why it's depth is `1` instead of `3` which is the source of the problem.

Currently, when the batch event fire, we mark which computes needed to be updated:

![presentation2](https://cloud.githubusercontent.com/assets/78602/16087630/48c14412-32e9-11e6-9988-4eb4a7d4656d.png)

And then update them in order of their depth.  `gg1` has the same depth as `c1` so it can be updated first.  Unfortunately, as `g1` is not being marked as needing to be updated, it will use its cached value.

So, we need to make sure that `c1` notifies `g1` as needing to be updated so that if read, it will update its own value.

**Comment by justinbmeyer** [comment]
btw, a work around for this is to read both computes no matter what.

**Comment by justinbmeyer** [comment]
This is closed.
